### ISSUE TITLE
Recommended method to migrate database

### ISSUE THREAD

**Issue by tomicakorac** [stevegrunwell/wordpress-git#1]
Hi Steve,

Sorry to bother you, I was reading your slides and at one point you say:

> New environments in four easy steps:
> Clone repository
> Import database
> Fill out wp-config.php
> Setup virtual host (if necessary)

Let's say I have a live site, a staging live version and a development local version. How would you recommend to keep databases synchronized among them? Since WP SQL data is serialized, it becomes tedious to manually export/import sql dumps among all three versions.

There is a plugin called WP Migrate DB, but I'm not sure if that's the best way. Plus, its Pro version is expensive as hell.

Can you please share a method how you do it?

Thanks.

**Comment by stevegrunwell** [comment]
Hi Томица,

This is one of the great quandaries when managing multiple WordPress environments, and while I don't have a simple answer, I'm happy to explain my typical approach:

At any given time, there should be **one canonical database** instance. During initial development, this may be your dev machine or on a shared staging site. Once the client begins editing the content somewhere (specifically **real** content editing, not just training via test posts), that database becomes the canonical source. Then, once a site is launched, production becomes the canonical database. If content has changed significantly on production, I'll occasionally dump the database and re-import into my dev and staging environments (that's where the mod_rewrite rule and the `WP_SITEURL`/`WP_HOME` constants come in handy). There will often be some lingering references to production, but I'd rather my dev/test site have some links to production rather than the other way around :)

If you want to fully update references to match the current environment you're working on, I'd recommend using [WP-CLI's search-replace command](http://wp-cli.org/commands/search-replace/), as it's designed to properly handle WordPress serialized data. Import the database, run the command, and you should be golden.

With regards to WP Migrate DB I've heard a lot about it, but have yet to hear overwhelmingly good or bad experiences from my peers. I haven't used the plugin myself, but @bradt and Delicious Brains have good reputations within the community, so if WP Migrate DB's workflow matches what you're looking for it may be worth giving it a try (especially as [Delicious Brains offers a 60-day satisfaction guarantee](https://deliciousbrains.com/wp-migrate-db-pro/pricing/#guarantee)).

Hopefully that helps!

**Comment by tomicakorac** [comment]
It sure does! I haven't had a chance to use wp-cli this far, but every now and then I hear an amazing thing about it. Since I always tend to automate my work as much as humanly possible, a cli command sounds like the way to go. I was also considering your first suggestion, but it sounds just a little bit more risky to me in case I cooperate with several other devs. I'd have to rely on their eloquence, and that's not always the safest way :)

I'm still considering the WP Migrate DB plugin. I've also found a lot of positive impressions online about it. But for some reason it just doesn't sound right to me to have to use a plugin just for that. Especially since it then becomes mandatory in all environments if I want to inter-change data among them.

Thank you once again. I love your presentations.
